[package]
name = "rjs-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"
oxc_parser = "0.30"
oxc_ast = "0.30"
oxc_span = "0.30"
oxc_allocator = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
